ttss_server:communicate_server.o
	g++ -o ttss_server communicate_server.o
communicate_server.o:communicate_server.cpp communicate_server.h
	g++ -c communicate_server.cpp
clean:
	rm -f communicate_server.o
